### ISSUE TITLE
server is not responding, is it CORS error?

### ISSUE THREAD

**Issue by VijayKodibailu** [jherr/graphql-jwt-speedrun#2]
cloned project and running after yarn install ...
when logging in from host app I got bellow response, 
also page is not displaying todos.

Headers:
Request URL: http://localhost:3000/
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: [::1]:3000
Referrer Policy: strict-origin-when-cross-origin

Preview:
errors: [{message: "Context creation failed: Cannot read property 'trim' of undefined",…}]

**Comment by jherr** [comment]
I just posted a README https://github.com/jherr/graphql-jwt-speedrun/blob/main/README.md that covers how to install and run. Could you clone again and follow those instructions and let me know if you are running into the issue. Because this code "works on my machine" (tm).
